site_name: OpenMarket Documentation
theme:
    name: readthedocs

nav:
  - Home: index.md
  - "How it works": how-the-dex-works.md
  - Architecture: architecture.md
  - "Client / Frontend integration": client-integration.md
  - Bootstrap: bootstrap.md